name: test
on: 
  workflow_dispatch:
    inputs:
      yourName:
        description: 'What is your name?'
        required: true
        default: 'Miguel'
      yourAge:
        description: 'What is your age?'
        required: false
        default: '10'
jobs:
  print-to-screen:
    runs-on: ubuntu-latest
    steps:
      - name: 'Greet workflow runner'
        run: echo "Hello ${{ github.event.inputs.yourName }}, you are ${{ github.event.inputs.yourAge }} years old"
