name: test
on: 
  workflow_dispatch:
    inputs:
      yourName:
        description: 'What is your name?'
        required: true
        default: 'Miguel'
  push:
    branches:
      - master
jobs:
  print-to-screen:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello Miguel, you are 26 years old"
      - uses: actions/checkout@v3