name: test
on: 
  workflow_dispatch:
    inputs:
      yourName:
        description: 'What is your name?'
        required: true
        default: 'Miguel'
  push:
    branches:
      - master
jobs:
  print-to-screen:
    runs-on: ubuntu-latest
    steps:
      - name: 'Greet workflow runner'
        run: |
          echo "Hello Miguel, you are 26 years old"
      - name: 'Copy repo code'
        uses: actions/checkout@v3